from fpdf import FPDF
import json
import datetime
import os

class SurvivalPDF(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 16)
        self.set_text_color(255, 0, 0)
        self.cell(0, 10, 'EMERGENCY SURVIVAL BRIEF', 0, 1, 'C')
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f'Page {self.page_no()} | Generated by Gemini Emergency Agent', 0, 0, 'C')

def generate_emergency_pdf(data, map_image="blast_map.png", output_path="emergency_brief.pdf"):
    """
    Generates a professional PDF report with integrated visuals.
    """
    pdf = SurvivalPDF()
    pdf.add_page()
    
    # Metadata
    pdf.set_font('Arial', '', 10)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 10, f"Timestamp: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", 0, 1)
    pdf.cell(0, 10, f"Status: CRITICAL", 0, 1)
    pdf.ln(5)
    
    # Sections
    sections = [
        ("1. IMPACT ANALYSIS", data.get("impact", "Data pending...")),
        ("2. EVACUATION ROUTE", data.get("evacuation", "Stay in shelter.")),
        ("3. POINTS OF INTEREST", "\n".join(data.get("poi", [])))
    ]
    
    for title, content in sections:
        pdf.set_font('Arial', 'B', 12)
        pdf.cell(0, 10, title, 0, 1)
        pdf.set_font('Arial', '', 11)
        pdf.multi_cell(0, 10, content)
        pdf.ln(5)
    
    # Integrated Visuals
    if os.path.exists(map_image):
        pdf.set_font('Arial', 'B', 12)
        pdf.cell(0, 10, "4. IMPACT VISUALIZATION", 0, 1)
        pdf.image(map_image, x=10, w=180)
        pdf.ln(5)
    
    # PFA Section
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 10, "5. PSYCHOLOGICAL FIRST AID", 0, 1)
    pdf.set_font('Arial', '', 11)
    pfa_text = "1. Grounding: 5-4-3-2-1 technique.\n2. Breathing: 4-7-8 method.\n3. Focus: Stay calm and follow the protocols."
    pdf.multi_cell(0, 10, pfa_text)
    
    pdf.output(output_path)
    print(f"PDF Report generated successfully at: {output_path}")
    return True

if __name__ == "__main__":
    # Example usage
    test_data = {
        "impact": "12kt Airburst over Besancon (47.2455, 6.0209). 2km Heavy Damage radius. EMP confirmed.",
        "evacuation": "A36 West toward Dole. Safe-exit vector identified. Avoid Luxeuil Airbase.",
        "poi": [
            "- Parking Marche Beaux-Arts (Deep Shelter)",
            "- CHRU Besancon (Medical - Limited Capacity)",
            "- Citadelle Tunnels (Alternative Shelter)"
        ]
    }
    generate_emergency_pdf(test_data)
